#配置开发环境内容
#port:映射端口，80端口的特殊端口（请求时可以不指定），实际项目中的服务器端口都是80
#context-path:配置项目启动路径
server:
  port: 8088
  servlet:
    context-path: /office

#JDBC配置,数据源四大金刚 等号前面是key，是固定写法，等号后面是根据自己的数据库来定义
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    #连接池配置
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 6000
      #获取连接时测试是否可用
      test-on-borrow: true
      #监控页面启动
      filters: stat
      #其他配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid


#mybatis配置
mybatis:
  mapper-locations: com/leixiaoqiao/mapper/xml/*.xml
  type-aliases-package: com.leixiaoqiao.pojo

#设置com.leixiaoqiao包的日志级别为debug（该种方式只能在控制台看到日志，所以只适合开发中使用）
logging:
  level:
    com:
      leixiaoqiao: debug

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql